id: AAADAD181
title: CVIII_Verses 161-180
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.820675
  last_modified_at: 2022-03-01 23:16:02.820678
