id: AAADAD181
title: CX_Verses 41-58
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.940584
  last_modified_at: 2022-03-01 23:16:02.940586
