id: AAADAD181
title: CIX_Verses 141-160
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.758219
  last_modified_at: 2022-03-01 23:16:02.758226
