id: AAADAD181
title: CIII_Verses 21-33
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.660793
  last_modified_at: 2022-03-01 23:16:02.660800
