id: AAADAD181
title: CVI_Verses 121-134
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.879059
  last_modified_at: 2022-03-01 23:16:02.879062
