id: AAADAD181
title: CVI_Verses 41-60
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.888577
  last_modified_at: 2022-03-01 23:16:02.888579
