id: AAADAD181
title: CVIII_Verses 61-80
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.839348
  last_modified_at: 2022-03-01 23:16:02.839351
