id: AAADAD181
title: CVIII_Verses 121-140
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.809871
  last_modified_at: 2022-03-01 23:16:02.809874
