id: AAADAD181
title: Colophon
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.942295
  last_modified_at: 2022-03-01 23:16:02.942297
