id: AAADAD181
title: CVII_Verses 61-75
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.865827
  last_modified_at: 2022-03-01 23:16:02.865830
