id: AAADAD181
title: CV_Verses 1-20
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.902497
  last_modified_at: 2022-03-01 23:16:02.902500
