id: AAADAD181
title: CVII_Verses 41-60
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.860315
  last_modified_at: 2022-03-01 23:16:02.860318
