id: AAADAD181
title: CIX_Verses 41-60
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.772087
  last_modified_at: 2022-03-01 23:16:02.772091
