id: AAADAD181
title: CII_Verses 21-40
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.674877
  last_modified_at: 2022-03-01 23:16:02.674885
