id: AAADAD181
title: CII_Verses 1-20
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.668190
  last_modified_at: 2022-03-01 23:16:02.668196
