id: AAADAD181
title: CV_Verses 81-100
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:16:02.924093
  last_modified_at: 2022-03-01 23:16:02.924095
